[package]
name = "streams"
version = "0.1.0"
authors = ["Ralph Bisschops <ralph.bisschops.dev@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", default-features = false, features = ["json"] }
tayvo_rocket_okapi = { version = "0.9.1", path = "../../rocket-okapi", features = ["swagger", "rapidoc"] }
serde = "1.0"
